// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzCZypjdnosISFYU8WeOQhtQr54NZIU2I',
    appId: '1:79958094131:web:87d51dc265ad210ea74e46',
    messagingSenderId: '79958094131',
    projectId: 'lost-found-proj2',
    authDomain: 'lost-found-proj2.firebaseapp.com',
    storageBucket: 'lost-found-proj2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMY4lhjxG1-zYRuGbiTpGf7YbxM7WG2Rk',
    appId: '1:79958094131:android:ccb426f8949947bfa74e46',
    messagingSenderId: '79958094131',
    projectId: 'lost-found-proj2',
    storageBucket: 'lost-found-proj2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFLZpcVwtHm1108h0nDmttqR2ypVdZhgM',
    appId: '1:79958094131:ios:8fc0a8d680a577c6a74e46',
    messagingSenderId: '79958094131',
    projectId: 'lost-found-proj2',
    storageBucket: 'lost-found-proj2.firebasestorage.app',
    iosBundleId: 'com.example.lostFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFLZpcVwtHm1108h0nDmttqR2ypVdZhgM',
    appId: '1:79958094131:ios:8fc0a8d680a577c6a74e46',
    messagingSenderId: '79958094131',
    projectId: 'lost-found-proj2',
    storageBucket: 'lost-found-proj2.firebasestorage.app',
    iosBundleId: 'com.example.lostFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzCZypjdnosISFYU8WeOQhtQr54NZIU2I',
    appId: '1:79958094131:web:82e9526cd1b5bb4aa74e46',
    messagingSenderId: '79958094131',
    projectId: 'lost-found-proj2',
    authDomain: 'lost-found-proj2.firebaseapp.com',
    storageBucket: 'lost-found-proj2.firebasestorage.app',
  );
}
